# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc1b6c5d122101f9ba4fa915d2a7ee6dcb4889d983d62c533661069b7c6f9d177cad099dd15c93b75ad3e42506999899c063399ddb2e82a360b21ca9891294d7

test:
  secret_key_base: ca357046492f6f1e7fe94c8f666159e434ededa9d80512b2bb160b23c58e9ec37d281693baba52508c07e2e1b74ae5bf512766df4cffd64057246ff3c6c5a4a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
